#yaml setting

version: '3'

services:
    elasticsearch:
        container_name: elasticsearch
        image: elasticsearch:7.5.2
         
        volumes:
        - "/opt/docker_ek_cowrie/ek/elasticsearch/data:/usr/share/elasticsearch/data"

        environment: 
            ES_JAVA_OPTS: "-Xms256m -Xmx256m"
            discovery.type: "single-node"

    kibana:
        container_name: kibana
        image: kibana:7.5.2

    nginx:
        container_name: nginx
        image: nginx:latest

        ports:
        - "8001:8001"
        volumes:
        - "/opt/docker_ek_cowrie/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
        - "/opt/docker_ek_cowrie/nginx/conf/passwd.db:/etc/nginx/passwd.db"


    cowrie:
        container_name: cowrie
        image: cowrie/cowrie:latest
        ports:
        - "2222:2222"
        - "23:2223"

        volumes:
        - "/opt/docker_ek_cowrie/cowrie/etc:/cowrie/cowrie-git/etc"
        - "/opt/docker_ek_cowrie/cowrie/downloads:/cowrie/cowrie-git/var/lib/cowrie/downloads"
